#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Dec 11 11:55:20 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

#OnlyOne is an application to remove duplicated files within a specified directory
#Copyright (C) 2014 Carlos Manuel Ferrás Hernández
#
#This file is part of OnlyOne.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of  MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

from PyQt4 import QtCore, QtGui
from functools import partial


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s
    
import os
#os.chdir('/usr/share/onlyone')

class Ui_MainWindow(object):	
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.setGeometry(QtCore.QRect(30,150,952, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("background-color: #ffffff;font-size: 13px; \n"))
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
		
	self.treeView = QtGui.QTableView()
	self.treeView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
	self.treeView.setStyleSheet(_fromUtf8("font-size: 11px;background:#f8f8f8;"))
	self.treeView.setObjectName(_fromUtf8("treeView"))
	self.treeView.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)

	self.pushButton_0 = QtGui.QPushButton()
        self.pushButton_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_0.setStyleSheet(_fromUtf8("color:#fff;border-radius:15px;"))
        self.pushButton_0.setText(_fromUtf8(""))
        icon= QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f12923089.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_0.setIcon(icon)
        self.pushButton_0.setIconSize(QtCore.QSize(30, 26))
        self.pushButton_0.setObjectName(_fromUtf8("pushButton_0"))	
        self.pushButton = QtGui.QPushButton()
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.pushButton.setStyleSheet(_fromUtf8("color:#fff;border-radius: 15px;"))
        self.pushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f12923088.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 26))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton()
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.pushButton_2.setStyleSheet(_fromUtf8("color:#fff;border-radius: 15px;"))
        self.pushButton_2.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f12904928.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton()
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet(_fromUtf8("color:#fff;border-radius: 15px;"))
        self.pushButton_3.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f2966728.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(36, 26))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton()
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_4.setStyleSheet(_fromUtf8("color:#fff;border-radius: 15px;text-align: left"))
        self.pushButton_4.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f12864728.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 26))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
	self.toolButton = QtGui.QToolButton(self.pushButton_4)
        self.toolButton.setGeometry(QtCore.QRect(34, 6, 13, 13))
	self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setStyleSheet(_fromUtf8("color:#fff;border-radius: 15px;"))
        self.toolButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f8577008-blue.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.toolButton_2 = QtGui.QToolButton(self.pushButton_4)
        self.toolButton_2.setGeometry(QtCore.QRect(3, 6, 13, 13))
	self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_2.setStyleSheet(_fromUtf8("color:#fff;border-radius: 15px;"))
        self.toolButton_2.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f8577009-blue.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.pushButton_5 = QtGui.QPushButton()
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet(_fromUtf8("color:#fff;border-radius: 15px;"))
        self.pushButton_5.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f13140384.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5555"))
	self.pushButton_5.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
	self.pushButton_55 = QtGui.QPushButton()
        self.pushButton_55.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_55.setStyleSheet(_fromUtf8("color:#fff;border-radius: 15px;"))
        self.pushButton_55.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/opacity.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_55.setIcon(icon4)
        self.pushButton_55.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_55.setObjectName(_fromUtf8("pushButton_55"))	
	self.pushButton_555 = QtGui.QPushButton()
        self.pushButton_555.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_555.setStyleSheet(_fromUtf8("color:#fff;border-radius: 15px;"))
        self.pushButton_555.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/defaultDirectory.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_555.setIcon(icon4)
        self.pushButton_555.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_555.setObjectName(_fromUtf8("pushButton_555"))		
        self.line_2 = QtGui.QFrame()
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame()
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
	self.label_14 = QtGui.QLabel()
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/logo.png")))
        self.label_14.setScaledContents(False)
        self.label_14.setObjectName(_fromUtf8("label_14"))       
	self.toolBox = QtGui.QToolBox()
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolBox.setStyleSheet(_fromUtf8("background-color:#ffffff;color:#094eb6;"))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))        
	
	self.page = QtGui.QWidget()	
        self.page.setObjectName(_fromUtf8("page"))	
	self.tabWidget = QtGui.QTabWidget()
	self.tabWidget.setFixedWidth(281)	
	self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
	self.layout_55 = QtGui.QHBoxLayout()
	self.layout_55.setSpacing(0)
	self.layout_55.setContentsMargins(0, 0,0, 0)
	self.layout_55.addWidget(self.tabWidget)
	self.page.setLayout(self.layout_55)
	
	self.tab_3 = QtGui.QWidget()	
        self.tab_3.setObjectName(_fromUtf8("tab_3"))		
	self.layout_1=QtGui.QGridLayout()	
	self.layout_1.setSpacing(0)
	self.layout_1.setContentsMargins(10, 10,10, 10)	
	self.label = QtGui.QLabel()
	self.layout_1.addWidget(self.label,0,0,1,-1)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel()
	self.layout_1.addWidget(self.label_2,4,0,1,-1)
        self.label_2.setObjectName(_fromUtf8("label_2"))	
	self.kurlrequester = QtGui.QListWidget()
	self.layout_1.addWidget(self.kurlrequester,1,0,3,5)
	self.kurlrequester .setAlternatingRowColors(True)	
        self.kurlrequester.setInputMethodHints(QtCore.Qt.ImhNone)
        self.kurlrequester.setFrameShape(QtGui.QFrame.Box)
        self.kurlrequester.setFrameShadow(QtGui.QFrame.Raised)
        self.kurlrequester.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.kurlrequester.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.kurlrequester.setTabKeyNavigation(True)
        self.kurlrequester.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.kurlrequester.setTextElideMode(QtCore.Qt.ElideNone)
        self.kurlrequester.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.kurlrequester.setProperty("isWrapping", False)
        self.kurlrequester.setResizeMode(QtGui.QListView.Adjust)
        self.kurlrequester.setLayoutMode(QtGui.QListView.Batched)
        self.kurlrequester.setViewMode(QtGui.QListView.ListMode)
        self.kurlrequester.setModelColumn(0)
        self.kurlrequester.setUniformItemSizes(True)
        self.kurlrequester.setWordWrap(False)
        self.kurlrequester.setSelectionRectVisible(False)
        self.kurlrequester.setObjectName(_fromUtf8(""))
	self.kurlrequester.setDefaultDropAction(QtCore.Qt.IgnoreAction)
	self.kurlrequester.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
	self.pushButton_kurlrequester = QtGui.QPushButton()
	self.layout_1.addWidget(self.pushButton_kurlrequester,1,5,1,1)
	icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
	self.pushButton_kurlrequester.setIcon(icon)
	self.pushButton_kurlrequester.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.pushButton_kurlrequester.setToolTip(QtGui.QApplication.translate("MainWindow", 'Adicionar directorio'))
        self.pushButton_kurlrequester.setObjectName(_fromUtf8("pushButton_kurlrequester"))
	self.pushButton_kurlrequester.setStyleSheet(_fromUtf8("border-radius:15px;"))		
	self.verticalSpacer_98 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
	self.layout_1.addItem(self.verticalSpacer_98,6,0,1,1)
	self.kurlrequester_2 = QtGui.QListWidget()
	self.layout_1.addWidget(self.kurlrequester_2,7,0,3,5)
	self.kurlrequester_2 .setAlternatingRowColors(True)	
        self.kurlrequester_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.kurlrequester_2.setFrameShape(QtGui.QFrame.Box)
        self.kurlrequester_2.setFrameShadow(QtGui.QFrame.Raised)
        self.kurlrequester_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.kurlrequester_2.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.kurlrequester_2.setTabKeyNavigation(True)
        self.kurlrequester_2.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.kurlrequester_2.setTextElideMode(QtCore.Qt.ElideNone)
        self.kurlrequester_2.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.kurlrequester_2.setProperty("isWrapping", False)
        self.kurlrequester_2.setResizeMode(QtGui.QListView.Adjust)
        self.kurlrequester_2.setLayoutMode(QtGui.QListView.Batched)
        self.kurlrequester_2.setViewMode(QtGui.QListView.ListMode)
        self.kurlrequester_2.setModelColumn(0)
        self.kurlrequester_2.setUniformItemSizes(True)
        self.kurlrequester_2.setWordWrap(False)
        self.kurlrequester_2.setSelectionRectVisible(False)
        self.kurlrequester_2.setObjectName(_fromUtf8(""))
	self.kurlrequester_2.setDefaultDropAction(QtCore.Qt.IgnoreAction)
	self.kurlrequester_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
	self.pushButton_kurlrequester_2= QtGui.QPushButton()
	self.pushButton_kurlrequester_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.layout_1.addWidget(self.pushButton_kurlrequester_2,7,5,1,1)
	icon.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
	self.pushButton_kurlrequester_2.setIcon(icon)
	self.pushButton_kurlrequester_2.setToolTip(QtGui.QApplication.translate("MainWindow", 'Adicionar directorio'))
        self.pushButton_kurlrequester_2.setObjectName(_fromUtf8("pushButton_kurlrequester_2"))
	self.pushButton_kurlrequester_2.setStyleSheet(_fromUtf8("border-radius:15px;"))
	self.tab_3.setLayout(self.layout_1)	
	self.tabWidget.addTab(self.tab_3, _fromUtf8(""))	
	
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))	
	self.layout_2=QtGui.QGridLayout()
	self.layout_2.setSpacing(5)
	self.layout_2.setContentsMargins(10, 10, 10, 10)
        self.label_6 = QtGui.QLabel()
	self.layout_2.addWidget(self.label_6,0,0,1,4)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel()
	self.layout_2.addWidget(self.label_7,0,4,1,4)
        self.label_7.setGeometry(QtCore.QRect(130, 10, 71, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))	
	self.lineEdit_2 = QtGui.QLineEdit()
	self.layout_2.addWidget(self.lineEdit_2,1,0,1,4)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 101, 23))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit()
	self.layout_2.addWidget(self.lineEdit_3,1,4,1,4)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 30, 101, 23))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
	self.pushButton_88 = QtGui.QPushButton()
	self.pushButton_88.setStyleSheet('background:#5DA5F4;border:2px solid #ffffff;color:#ffffff;font-weight: bold;font-size:14px;')
	self.pushButton_88.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.layout_2.addWidget(self.pushButton_88,2,1,1,1)
        self.pushButton_88.setGeometry(QtCore.QRect(25, 60, 33, 27))
        self.pushButton_88.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f11062728.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_88.setIcon(icon1)
	self.pushButton_88.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_88.setObjectName(_fromUtf8("pushButton_88"))
        self.pushButton_85 = QtGui.QPushButton()
	self.pushButton_85.setStyleSheet('background:#5DA5F4;border:2px solid #ffffff;color:#ffffff;font-weight: bold;font-size:14px;')
	self.pushButton_85.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.layout_2.addWidget(self.pushButton_85,2,5,1,1)
        self.pushButton_85.setGeometry(QtCore.QRect(145, 60, 33, 27))
        self.pushButton_85.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f11062728.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_85.setIcon(icon2)
	self.pushButton_85.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_85.setObjectName(_fromUtf8("pushButton_85"))
	self.pushButton_87 = QtGui.QPushButton()
	self.pushButton_87.setStyleSheet('background:#5DA5F4;border:2px solid #ffffff;color:#ffffff;font-weight: bold;font-size:14px;')
	self.pushButton_87.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.layout_2.addWidget(self.pushButton_87,2,2,1,1)
        self.pushButton_87.setGeometry(QtCore.QRect(65, 60, 33, 27))
        self.pushButton_87.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f6447422.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_87.setIcon(icon1)
	self.pushButton_87.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_87.setObjectName(_fromUtf8("pushButton_87"))
        self.pushButton_89 = QtGui.QPushButton()
	self.pushButton_89.setStyleSheet('background:#5DA5F4;border:2px solid #ffffff;color:#ffffff;font-weight: bold;font-size:14px;')
	self.pushButton_89.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.layout_2.addWidget(self.pushButton_89,2,6,1,1)
        self.pushButton_89.setGeometry(QtCore.QRect(185, 60, 33, 27))
        self.pushButton_89.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f6447422.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_89.setIcon(icon2)
	self.pushButton_89.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_89.setObjectName(_fromUtf8("pushButton_89"))	
	self.listWidget_3 = QtGui.QListWidget()
	self.layout_2.addWidget(self.listWidget_3,3,0,4,4)
        self.listWidget_3.setGeometry(QtCore.QRect(10, 90, 101, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_3.sizePolicy().hasHeightForWidth())
        self.listWidget_3.setSizePolicy(sizePolicy)
        self.listWidget_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listWidget_3.setFrameShape(QtGui.QFrame.Box)
        self.listWidget_3.setFrameShadow(QtGui.QFrame.Raised)
        self.listWidget_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_3.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.listWidget_3.setTabKeyNavigation(True)
        self.listWidget_3.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listWidget_3.setTextElideMode(QtCore.Qt.ElideNone)
        self.listWidget_3.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.listWidget_3.setProperty("isWrapping", False)
        self.listWidget_3.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget_3.setLayoutMode(QtGui.QListView.Batched)
        self.listWidget_3.setViewMode(QtGui.QListView.ListMode)
        self.listWidget_3.setModelColumn(0)
        self.listWidget_3.setUniformItemSizes(True)
        self.listWidget_3.setWordWrap(False)
        self.listWidget_3.setSelectionRectVisible(False)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget"))
	self.listWidget_3.setDefaultDropAction(QtCore.Qt.IgnoreAction)
	self.listWidget_4 = QtGui.QListWidget()
	self.layout_2.addWidget(self.listWidget_4,3,4,4,4)
        self.listWidget_4.setGeometry(QtCore.QRect(130, 90, 101, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_4.sizePolicy().hasHeightForWidth())
        self.listWidget_4.setSizePolicy(sizePolicy)
        self.listWidget_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listWidget_4.setFrameShape(QtGui.QFrame.Box)
        self.listWidget_4.setFrameShadow(QtGui.QFrame.Raised)
        self.listWidget_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_4.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.listWidget_4.setTabKeyNavigation(True)
        self.listWidget_4.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listWidget_4.setTextElideMode(QtCore.Qt.ElideNone)
        self.listWidget_4.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.listWidget_4.setProperty("isWrapping", False)
        self.listWidget_4.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget_4.setLayoutMode(QtGui.QListView.Batched)
        self.listWidget_4.setViewMode(QtGui.QListView.ListMode)
        self.listWidget_4.setModelColumn(0)
        self.listWidget_4.setUniformItemSizes(True)
        self.listWidget_4.setWordWrap(False)
        self.listWidget_4.setSelectionRectVisible(False)
        self.listWidget_4.setObjectName(_fromUtf8(""))
	self.listWidget_4.setDefaultDropAction(QtCore.Qt.IgnoreAction)
	self.verticalSpacer_1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
	self.layout_2.addItem(self.verticalSpacer_1,4,0,15,1)
	self.tab.setLayout(self.layout_2)	
	self.listWidget = QtGui.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(10, 53, 128, 111))
        self.listWidget.setTabKeyNavigation(True)
        self.listWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.listWidget.setViewMode(QtGui.QListView.ListMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setWordWrap(False)
        self.listWidget.setSelectionRectVisible(False)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))	
	self.listWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
	self.listWidget.setVisible(False)
	self.listWidget_2 = QtGui.QListWidget(self.tab)
        self.listWidget_2.setGeometry(QtCore.QRect(142, 53, 125, 111))
        self.listWidget_2.setTabKeyNavigation(True)
        self.listWidget_2.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
	self.listWidget_2.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.listWidget_2.setViewMode(QtGui.QListView.ListMode)
        self.listWidget_2.setModelColumn(0)
        self.listWidget_2.setUniformItemSizes(True)
        self.listWidget_2.setWordWrap(False)
        self.listWidget_2.setSelectionRectVisible(False)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget"))
	self.listWidget_2.setDefaultDropAction(QtCore.Qt.IgnoreAction)
	self.listWidget_2.setVisible(False)	
	self.tabWidget.addTab(self.tab, _fromUtf8(""))
	
	self.checkBox_5 = QtGui.QCheckBox()
	self.layout_2.addWidget(self.checkBox_5,8,0,1,4)
	self.checkBox_6 = QtGui.QCheckBox()
	self.layout_2.addWidget(self.checkBox_6,9,0,1,4)
	self.checkBox_9 = QtGui.QCheckBox()
	self.layout_2.addWidget(self.checkBox_9,10,0,1,4)
	self.checkBox_7 = QtGui.QCheckBox()
	self.layout_2.addWidget(self.checkBox_7,8,4,1,4)
	self.checkBox_8 = QtGui.QCheckBox()
	self.layout_2.addWidget(self.checkBox_8,9,4,1,4)
	self.checkBox_10 = QtGui.QCheckBox()
	self.layout_2.addWidget(self.checkBox_10,10,4,1,4)
	
	self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
	self.layout_3=QtGui.QGridLayout()
	self.layout_3.setSpacing(10)
	self.layout_3.setContentsMargins(10, 10, 10, 10)
        self.label_5 = QtGui.QLabel()
	self.layout_3.addWidget(self.label_5,0,0,1,-1)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 200, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
	self.label_3 = QtGui.QLabel()
	self.layout_3.addWidget(self.label_3,1,0,1,2)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 90, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel()
	self.layout_3.addWidget(self.label_4,2,0,1,2)
        self.label_4.setGeometry(QtCore.QRect(10, 110,90, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox()
	self.layout_3.addWidget(self.doubleSpinBox,1,2,1,2)
        self.doubleSpinBox.setGeometry(QtCore.QRect(90, 60, 80, 23))
	self.doubleSpinBox.setMaximum(999999999999999999.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox()
	self.layout_3.addWidget(self.doubleSpinBox_2,2,2,1,2)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(90, 110, 80, 23))
	self.doubleSpinBox_2.setMaximum(9999999999999999999.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))        
	self.comboBox = QtGui.QComboBox()
	self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.layout_3.addWidget(self.comboBox,1,4,1,3)
        self.comboBox.setGeometry(QtCore.QRect(180, 60, 70, 23))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8("B"))
	self.comboBox.addItem(_fromUtf8("KB"))
	self.comboBox.addItem(_fromUtf8("MB"))
	self.comboBox.addItem(_fromUtf8("GB"))
	self.comboBox_2 = QtGui.QComboBox()
	self.comboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.layout_3.addWidget(self.comboBox_2,2,4,1,3)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 110, 70, 23))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8("B"))
	self.comboBox_2.addItem(_fromUtf8("KB"))
	self.comboBox_2.addItem(_fromUtf8("MB"))
	self.comboBox_2.addItem(_fromUtf8("GB"))	
	self.verticalSpacer = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
	self.layout_3.addItem(self.verticalSpacer,3,0,1,1)	
	self.tab_2.setLayout(self.layout_3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
	
	icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f6178612.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon5, _fromUtf8(""))
        
	self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
	self.layout_555 = QtGui.QGridLayout()
	self.layout_555.setSpacing(5)
	self.layout_555.setContentsMargins(10,10,10,10)		
	self.hash=QtGui.QLabel()	
	self.layout_555.addWidget(self.hash,1,0,1,2)
	self.radio1=QtGui.QRadioButton()
	self.radio1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.radio1.setText('MD2')
	self.layout_555.addWidget(self.radio1,2,0,1,1)	
	self.radio2=QtGui.QRadioButton()
	self.radio2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.radio2.setText('MD4')
	self.layout_555.addWidget(self.radio2,3,0,1,1)
	self.radio3=QtGui.QRadioButton()
	self.radio3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.radio3.setChecked(True)
	self.radio3.setText('MD5')
	self.layout_555.addWidget(self.radio3,4,0,1,1)
	self.radio4=QtGui.QRadioButton()
	self.radio4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.radio4.setText('SHA224')
	self.layout_555.addWidget(self.radio4,5,0,1,1)
	self.radio5=QtGui.QRadioButton()
	self.radio5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.radio5.setText('SHA256')
	self.layout_555.addWidget(self.radio5,6,0,1,1)
	self.radio6=QtGui.QRadioButton()
	self.radio6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.radio6.setText('SHA512')
	self.layout_555.addWidget(self.radio6,7,0,1,1)	
	self.pushButton_6 = QtGui.QPushButton()
	self.layout_555.addWidget(self.pushButton_6,8,0,1,2)
        self.pushButton_6.setGeometry(QtCore.QRect(5, 20, 200, 27))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.pushButton_6.setStyleSheet('text-align: left;background:#5DA5F4;border:2px solid #ffffff;color:#ffffff;padding:5px;font-weight: bold;font-size:14px;')
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f11046904.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
	self.pushButton_666 = QtGui.QPushButton()
	self.layout_555.addWidget(self.pushButton_666,8,0,1,2)
        self.pushButton_666.setGeometry(QtCore.QRect(5, 20, 200, 27))
        self.pushButton_666.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.pushButton_666.setStyleSheet('text-align: left;background:#5DA5F4;border:2px solid #ffffff;color:#ffffff;padding:5px;font-weight: bold;font-size:14px;')
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f11046904.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_666.setIcon(icon6)
        self.pushButton_666.setObjectName(_fromUtf8("pushButton_666"))
	self.pushButton_666.setVisible(False)
        self.pushButton_7 = QtGui.QPushButton()
	self.layout_555.addWidget(self.pushButton_7,10,0,1,2)
        self.pushButton_7.setGeometry(QtCore.QRect(5, 70, 200, 27))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.pushButton_7.setStyleSheet('text-align: left;background:#5DA5F4;border:2px solid #ffffff;color:#ffffff;padding:5px;font-weight: bold;font-size:14px;')
	self.progressBar = QtGui.QProgressBar()
	self.layout_555.addWidget(self.progressBar,9,0,1,2)
	self.progressBar.setRange(0,1)
	self.progressBar.setGeometry(QtCore.QRect(207, 22, 50, 22))
	self.progressBar.setObjectName(_fromUtf8("progressBar"))
	self.progressBar.show()
	self.progressBar.setVisible(False)	
	self.progressBar_2 = QtGui.QProgressBar()
	self.layout_555.addWidget(self.progressBar_2,11,0,1,2)
	self.progressBar_2.setRange(0,1)
	self.progressBar_2.setGeometry(QtCore.QRect(207, 72, 50, 22))
	self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
	self.progressBar_2.show()
	self.progressBar_2.setVisible(False)	
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f6618952.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon7)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))	
        icon99 = QtGui.QIcon()
        icon99.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f6188318.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
	self.verticalSpacer_55 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
	self.layout_555.addItem(self.verticalSpacer_55,12,0,1,1)	
	self.page_2.setLayout(self.layout_555)
	self.toolBox.addItem(self.page_2, icon99, _fromUtf8(""))        
	
	self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
	self.layout_5555 = QtGui.QGridLayout()
	self.layout_5555.setSpacing(5)
	self.layout_5555.setContentsMargins(10,10,10,10)
        self.pushButton_14 = QtGui.QPushButton()
	self.layout_5555.addWidget(self.pushButton_14,1,0,1,4)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 10, 231, 27))
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.pushButton_14.setStyleSheet('text-align: left;background:#5DA5F4;border:2px solid #ffffff;color:#ffffff;padding:5px;font-weight: bold;font-size:14px;')
	icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f6447422.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon9)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton()
	self.layout_5555.addWidget(self.pushButton_15,2,0,1,4)
        self.pushButton_15.setGeometry(QtCore.QRect(20, 50, 231, 27))
        self.pushButton_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.pushButton_15.setStyleSheet('text-align: left;background:#5DA5F4;border:2px solid #ffffff;color:#ffffff;padding:5px;font-weight: bold;font-size:14px;')
        self.pushButton_15.setIcon(icon9)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton()
	self.layout_5555.addWidget(self.pushButton_16,3,0,1,4)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 90, 231, 27))
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.pushButton_16.setStyleSheet('text-align: left;background:#5DA5F4;border:2px solid #ffffff;color:#ffffff;padding:5px;font-weight: bold;font-size:14px;')
        self.pushButton_16.setIcon(icon9)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.pushButton_17 = QtGui.QPushButton()
	self.layout_5555.addWidget(self.pushButton_17,4,0,1,4)
        self.pushButton_17.setGeometry(QtCore.QRect(20, 130, 231, 27))
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.pushButton_17.setStyleSheet('text-align: left;background:#5DA5F4;border:2px solid #ffffff;color:#ffffff;padding:5px;font-weight: bold;font-size:14px;')
        self.pushButton_17.setIcon(icon9)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))	
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f13139072.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
	self.verticalSpacer_555 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
	self.layout_5555.addItem(self.verticalSpacer_555,5,0,1,1)	
	self.page_3.setLayout(self.layout_5555)
	self.toolBox.addItem(self.page_3, icon10, _fromUtf8(""))
        
	self.groupBox_2 = QtGui.QGroupBox()
        self.groupBox_2.setStyleSheet(_fromUtf8("background-color:#5DA5F4;"))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pushButton_66 = QtGui.QPushButton()
        self.pushButton_66.setGeometry(QtCore.QRect(550, 6, 47, 31))
        self.pushButton_66.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_66.setText(_fromUtf8(""))
	self.pushButton_66.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
	self.pushButton_66.setIcon(icon99)
        self.pushButton_66.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_66.setObjectName(_fromUtf8("pushButton_10"))
        self.lineEdit = QtGui.QLineEdit()
        self.lineEdit.setGeometry(QtCore.QRect(430, 10, 113, 23))
        self.lineEdit.setStyleSheet(_fromUtf8("background-color:#ffffff;"))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton_10 = QtGui.QPushButton()
        self.pushButton_10.setGeometry(QtCore.QRect(10, 6, 47, 31))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setText(_fromUtf8(""))
	self.pushButton_10.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f8576560.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon11)
        self.pushButton_10.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton()
        self.pushButton_11.setGeometry(QtCore.QRect(80, 6, 47, 31))
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setText(_fromUtf8(""))
	self.pushButton_11.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f8576576.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon12)
        self.pushButton_11.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_12 = QtGui.QPushButton()
        self.pushButton_12.setGeometry(QtCore.QRect(150, 6, 47, 31))
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setText(_fromUtf8(""))
	self.pushButton_12.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/este.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon13)
        self.pushButton_12.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton()
        self.pushButton_13.setGeometry(QtCore.QRect(610, 6, 47, 31))
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setText(_fromUtf8(""))
	self.pushButton_13.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
	icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/options.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
	self.pushButton_13.setIcon(icon12)
        self.pushButton_13.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
	self.pushButton_13.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
	self.pushButton_74 = QtGui.QPushButton()
        self.pushButton_74.setGeometry(QtCore.QRect(80, 6, 47, 31))
        self.pushButton_74.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_74.setText(_fromUtf8(""))
	self.pushButton_74.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f85765762.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_74.setIcon(icon12)
        self.pushButton_74.setIconSize(QtCore.QSize(26, 26))
	self.pushButton_75 = QtGui.QPushButton()
        self.pushButton_75.setGeometry(QtCore.QRect(80, 6, 47, 31))
        self.pushButton_75.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_75.setText(_fromUtf8(""))
	self.pushButton_75.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f85765763.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_75.setIcon(icon12)
        self.pushButton_75.setIconSize(QtCore.QSize(26, 26))
        
	self.groupBox_3 = QtGui.QWidget()
        self.groupBox_3.setStyleSheet(_fromUtf8("background-color:#d0deed;"))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))	
	self.verticalLayout = QtGui.QGridLayout(self.groupBox_3)
	self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(10, 0, 0, 0)	
	self.label_15 = QtGui.QLabel()
	self.verticalLayout.addWidget(self.label_15,0,0,1,3)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 160, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
	self.label_16 = QtGui.QLabel()
	self.verticalLayout.addWidget(self.label_16,2,0,1,3)
        self.label_16.setGeometry(QtCore.QRect(10, 40, 160, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
	self.label_20 = QtGui.QLabel()
	self.verticalLayout.addWidget(self.label_20,4,0,1,3)
        self.label_20.setGeometry(QtCore.QRect(10, 70, 160, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
	self.label_20.setVisible(False)
        self.label_19 = QtGui.QLabel()
	self.verticalLayout.addWidget(self.label_19,6,0,1,3)
        self.label_19.setGeometry(QtCore.QRect(10, 100, 160, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
	self.label_19.setVisible(False)
        self.label_18 = QtGui.QLabel()
	self.verticalLayout.addWidget(self.label_18,8,0,1,3)
        self.label_18.setGeometry(QtCore.QRect(10, 130, 160, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
	self.label_18.setVisible(False)
        self.label_17 = QtGui.QLabel()
	self.verticalLayout.addWidget(self.label_17,10,0,1,3)
        self.label_17.setGeometry(QtCore.QRect(10, 160, 160, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
	self.label_17.setVisible(False)
	self.label_8 = QtGui.QLabel()
	self.verticalLayout.addWidget(self.label_8,0,4,1,2)
        self.label_8.setGeometry(QtCore.QRect(175, 10, 79, 17))
	self.label_8.setStyleSheet(_fromUtf8("color:#1a528f;\n"
"font-weight:bold"))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel()
	self.verticalLayout.addWidget(self.label_9,2,4,1,2)
        self.label_9.setGeometry(QtCore.QRect(175, 40, 79, 17))
	self.label_9.setStyleSheet(_fromUtf8("color:#1a528f;\n"
"font-weight:bold"))
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel()
	self.verticalLayout.addWidget(self.label_10,4,4,1,2)
        self.label_10.setGeometry(QtCore.QRect(175, 70, 79, 17))
	self.label_10.setStyleSheet(_fromUtf8("color:#1a528f;\n"
"font-weight:bold"))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel()
	self.verticalLayout.addWidget(self.label_11,6,4,1,2)
        self.label_11.setGeometry(QtCore.QRect(175, 100, 88, 17))
	self.label_11.setStyleSheet(_fromUtf8("color:#1a528f;\n"
"font-weight:bold"))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel()
	self.verticalLayout.addWidget(self.label_12,8,4,1,2)
        self.label_12.setGeometry(QtCore.QRect(175, 130, 88, 17))
	self.label_12.setStyleSheet(_fromUtf8("color:#1a528f;\n"
"font-weight:bold"))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel()
	self.verticalLayout.addWidget(self.label_13,10,4,1,2)
        self.label_13.setGeometry(QtCore.QRect(175, 160, 88, 17))
	self.label_13.setStyleSheet(_fromUtf8("color:#1a528f;\n"
"font-weight:bold"))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))	
	self.groupBox_3.setLayout(self.verticalLayout)
      
	self.groupBox_4 = QtGui.QGroupBox()
        self.groupBox_4.setStyleSheet(_fromUtf8("background-color:#5DA5F4;"))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.icon14 = QtGui.QIcon()
        self.icon14.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f6864248.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
	self.icon141 = QtGui.QIcon()
        self.icon141.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/asdf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
	self.label_98 = QtGui.QLabel()
        self.label_98.setGeometry(QtCore.QRect(1, 2, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_98.setFont(font)
	self.label_98.setVisible(False)
        self.label_98.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 12px;background-color:#5DA5F4;"))
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.label_99 = QtGui.QLabel()
        self.label_99.setGeometry(QtCore.QRect(130, 2, 150, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_99.setFont(font)
        self.label_99.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 12px;background-color:#5DA5F4;"))
        self.label_99.setText(_fromUtf8(""))
        self.label_99.setObjectName(_fromUtf8("label_99"))
	self.label_988 = QtGui.QLabel()
        self.label_988.setGeometry(QtCore.QRect(270, 2, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_988.setFont(font)
	self.label_988.setVisible(False)
        self.label_988.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 12px;background-color:#5DA5F4;"))
        self.label_988.setObjectName(_fromUtf8("label_988"))
        self.label_999 = QtGui.QLabel()
        self.label_999.setGeometry(QtCore.QRect(390, 2, 59, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_999.setFont(font)
        self.label_999.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 12px;background-color:#5DA5F4;"))
        self.label_999.setText(_fromUtf8(""))
        self.label_999.setObjectName(_fromUtf8("label_999"))	
	self.label_9888 = QtGui.QPushButton()
	self.label_9888.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_9888.setGeometry(QtCore.QRect(487, -10, 50, 38))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9888.setFont(font)
	self.label_9888.setVisible(False)
        self.label_9888.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
        self.label_9888.setObjectName(_fromUtf8("label_9888"))
	icon243= QtGui.QIcon()
        icon243.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/folder-empty-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.label_9888.setIcon(icon243)
	self.label_9888.setIconSize(QtCore.QSize(30,30))        
	self.label_9999 = QtGui.QLabel()
        self.label_9999.setGeometry(QtCore.QRect(534, 2, 59, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9999.setFont(font)
        self.label_9999.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 12px;background-color:#5DA5F4;"))
        self.label_9999.setText(_fromUtf8(""))
        self.label_9999.setObjectName(_fromUtf8("label_999"))	
	self.label_98888 = QtGui.QPushButton()
	self.label_98888.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_98888.setGeometry(QtCore.QRect(570, -5, 50, 38))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_98888.setFont(font)
	self.label_98888.setVisible(False)
        self.label_98888.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
        self.label_98888.setObjectName(_fromUtf8("label_98888"))
        icon243= QtGui.QIcon()
        icon243.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/temp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.label_98888.setIcon(icon243)
	self.label_98888.setIconSize(QtCore.QSize(25,25))	
	self.label_99999 = QtGui.QLabel()
        self.label_99999.setGeometry(QtCore.QRect(615, 2, 59, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_99999.setFont(font)
        self.label_99999.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 12px;background-color:#5DA5F4;"))
        self.label_99999.setText(_fromUtf8(""))
        self.label_99999.setObjectName(_fromUtf8("label_9999"))
	
	self.centralwidget=QtGui.QWidget()
	MainWindow.setCentralWidget(self.centralwidget)		
	self.layout=QtGui.QGridLayout(self.centralwidget)
	self.layout.setSpacing(0)
	self.layout.setHorizontalSpacing(2)
	self.layout.setContentsMargins(0, 0, 0, 0)
	
	self.centralwidget.setStyleSheet(_fromUtf8("background-color: #555555;"))
	
	#arriba
	self.layout.addWidget(self.line_2, 0, 0, 1, 2)
	self.layout.addWidget(self.label_14, 0, 1, 1, 2)
	self.layout.addWidget(self.line_3, 0, 2, 1, 10)
	self.layout.addWidget(self.pushButton_5, 0, 12, 1, 1)
	self.layout.addWidget(self.pushButton_555, 0, 13, 1, 1)
	self.layout.addWidget(self.pushButton_55, 0, 14, 1, 1)	
	self.layout.addWidget(self.pushButton_4, 0, 15, 1, 1)
	self.layout.addWidget(self.pushButton_2, 0, 16, 1, 1)
	self.layout.addWidget(self.pushButton_3, 0, 17, 1, 1)
	self.layout.addWidget(self.pushButton_0, 0, 18, 1, 1)
	self.layout.addWidget(self.pushButton, 0, 19, 1, 1)
	#isquierda-arriba
	self.layout.addWidget(self.toolBox, 1, 0, 14, 6)
	#isquierda-abajo
	self.layout.addWidget(self.groupBox_3,15,0,9,6)
	#derecha-arriba	
	self.layout.addWidget(self.groupBox_2,1,6,2,14)
	self.layout.addWidget(self.pushButton_10,1,6,2,1)
	self.layout.addWidget(self.pushButton_12,1,7,2,1)
	self.layout.addWidget(self.pushButton_11,1,8,2,1)
	self.layout.addWidget(self.pushButton_74,1,9,2,1)
	self.layout.addWidget(self.pushButton_75,1,10,2,1)
	self.layout.addWidget(self.lineEdit,1,15,2,3)
	self.layout.addWidget(self.pushButton_66,1,18,2,1)
	self.layout.addWidget(self.pushButton_13,1,19,2,1)	
	#derecha-medio
	self.layout.addWidget(self.treeView,3,6,20,14)	
	#derecha-abajo
	self.layout.addWidget(self.groupBox_4,23,6,1,14)	
	self.layout.addWidget(self.label_98,23,6,1,3)
	self.layout.addWidget(self.label_99,23,9,1,3)
	self.layout.addWidget(self.label_988,23,12,1,2)
	self.layout.addWidget(self.label_999,23,14,1,2)
	self.layout.addWidget(self.label_9888,23,16,1,1)
	self.layout.addWidget(self.label_9999,23,17,1,1)
	self.layout.addWidget(self.label_98888,23,18,1,1)	
	self.layout.addWidget(self.label_99999,23,19,1,1)
	
	self.layout.setRowMinimumHeight(1,18)
	self.layout.setRowMinimumHeight(2,18)
	self.layout.setRowMinimumHeight(23,23)
	
	for i in range(6):
		self.layout.setColumnMinimumWidth(i,50)
	
	#panel desplegable
	self.widget_09 = QtGui.QWidget()	
	self.widget_09.setStyleSheet("background:#5DA5F4")
	self.widget_09.setObjectName("widget")	
	self.layout_09 = QtGui.QGridLayout()
	self.layout_09.setContentsMargins(3,3,3,3)	
	self.listWidget_09 = QtGui.QListWidget()
	self.layout_09.addWidget(self.listWidget_09,1,0,20,10)
	self.listWidget_09.setStyleSheet("background:#ffffff")
	self.listWidget_09.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)	
	self.listWidget_09.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
	self.pushButton_09 = QtGui.QPushButton()
	self.pushButton_09.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.pushButton_09.setToolTip(QtGui.QApplication.translate("MainWindow",'Borrar todos', None, QtGui.QApplication.UnicodeUTF8))
	icon09 = QtGui.QIcon()
        icon09.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f6447422.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_09.setIcon(icon09)
	self.pushButton_09.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
	self.layout_09.addWidget(self.pushButton_09,0,8,1,1)
	self.pushButton_099 = QtGui.QPushButton()
	self.pushButton_099.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.pushButton_099.setToolTip(QtGui.QApplication.translate("MainWindow",'Borrar marcados', None, QtGui.QApplication.UnicodeUTF8))
	icon09 = QtGui.QIcon()
        icon09.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/delete-seleccion.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_099.setIcon(icon09)
	self.pushButton_099.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
	self.layout_09.addWidget(self.pushButton_099,0,9,1,1)	
	self.pushButton_0999 = QtGui.QPushButton()
	self.pushButton_0999.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.pushButton_0999.setToolTip(QtGui.QApplication.translate("MainWindow",'Borrar todos', None, QtGui.QApplication.UnicodeUTF8))
	icon09 = QtGui.QIcon()
        icon09.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/f6447422.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_0999.setIcon(icon09)
	self.pushButton_0999.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
	self.layout_09.addWidget(self.pushButton_0999,0,8,1,1)
	self.pushButton_09999 = QtGui.QPushButton()
	self.pushButton_09999.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.pushButton_09999.setToolTip(QtGui.QApplication.translate("MainWindow",'Borrar marcados', None, QtGui.QApplication.UnicodeUTF8))
	icon09 = QtGui.QIcon()
        icon09.addPixmap(QtGui.QPixmap(_fromUtf8("pixmaps/onlyone/delete-seleccion.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_09999.setIcon(icon09)
	self.pushButton_09999.setStyleSheet(_fromUtf8("background-color:#5DA5F4;border-radius:15px;"))
	self.layout_09.addWidget(self.pushButton_09999,0,9,1,1)	
	self.pushButton_09.setVisible(False)
	self.pushButton_099.setVisible(False)
	self.pushButton_0999.setVisible(False)
	self.pushButton_09999.setVisible(False)	
	self.label_09 = QtGui.QLabel()
	self.layout_09.addWidget(self.label_09,0,0,1,6)
	self.label_09.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
	self.label_09.setStyleSheet("color:#ffffff")
	self.label_09.setObjectName("label")
	self.label_099 = QtGui.QLabel()
	self.layout_09.addWidget(self.label_099,0,6,1,1)
	self.label_099.setStyleSheet("color:#ffffff")
	self.label_099.setObjectName("label_2")		
	self.label_0999 = QtGui.QLabel()
	self.label_0999.setStyleSheet("color:#ffffff")
	self.layout_09.addWidget(self.label_0999,20,0,1,6)
	self.label_0999.setHidden(True)
	self.label_09999 = QtGui.QLabel()
	self.label_09999.setStyleSheet("color:#ffffff")
	self.layout_09.addWidget(self.label_09999,20,5,1,5)
	self.label_09999.setHidden(True)		
	self.frame_999=QtGui.QFrame()
	self.layout_09.addWidget(self.frame_999,1,0,1,10)
	self.layout_099 = QtGui.QGridLayout()
	self.layout_099.setContentsMargins(3,3,3,3)
	self.frame_999.setHidden(True)
	self.frame_999.setStyleSheet("background:#ffffff;border:3px solid #5DA5F4")	
	self.label_099999 = QtGui.QLabel()
	self.label_099999.setStyleSheet("color:#5DA5F4;border:0;")
	self.layout_099.addWidget(self.label_099999,0,0,1,6)
	self.comboBox_099999 = QtGui.QComboBox()
	self.comboBox_099999.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.comboBox_099999.setStyleSheet("color:#5DA5F4;border:1px solid #5DA5F4;")
	self.layout_099.addWidget(self.comboBox_099999,0,6,1,4)	
	self.comboBox_099999.addItem("All")
	self.comboBox_099999.addItem("*.tmp")
        self.comboBox_099999.addItem("*.bak")
        self.comboBox_099999.addItem("*.db")
	self.comboBox_099999.addItem("*~")
	self.comboBox_099999.addItem("*.log")
        self.comboBox_099999.addItem("*.diz")
        self.comboBox_099999.addItem("*.pure")
	self.comboBox_099999.addItem("*.pyc")
        self.comboBox_099999.addItem("*.swp")
        self.comboBox_099999.addItem("*.lo")
	self.comboBox_099999.addItem("*.o")
        self.comboBox_099999.addItem("*.v")
        self.comboBox_099999.addItem("*.ion")
	
	self.frame_999.setLayout(self.layout_099)
	
	self.widget_09.setLayout(self.layout_09)
	self.widget_09.show()		
	self.layout.addWidget(self.widget_09,10,14,13,5)	
	self.widget_09.setVisible(False)
	
        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OnlyOne", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", 'Acerca de...', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_0.setToolTip(QtGui.QApplication.translate("MainWindow", "Twitter", None, QtGui.QApplication.UnicodeUTF8))
	self.pushButton_2.setToolTip(QtGui.QApplication.translate("MainWindow", 'Ayuda', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setToolTip(QtGui.QApplication.translate("MainWindow", 'Contáctenos en Facebook', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setToolTip(QtGui.QApplication.translate("MainWindow", 'Tipografía', None, QtGui.QApplication.UnicodeUTF8))
	self.toolButton.setToolTip(QtGui.QApplication.translate("MainWindow", 'Tipografía'+"++", None, QtGui.QApplication.UnicodeUTF8))
	self.toolButton_2.setToolTip(QtGui.QApplication.translate("MainWindow", 'Tipografía'+"--", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setToolTip(QtGui.QApplication.translate("MainWindow", 'Idioma', None, QtGui.QApplication.UnicodeUTF8))
	self.pushButton_55.setToolTip(QtGui.QApplication.translate("MainWindow", 'Opacidad', None, QtGui.QApplication.UnicodeUTF8))
	self.pushButton_555.setToolTip(QtGui.QApplication.translate("MainWindow", 'Directorio por defecto', None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", 'Realizar búsqueda en los directorios:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", 'No incluir los directorios:', None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", 'Por Carpeta', None, QtGui.QApplication.UnicodeUTF8))
        self.hash.setText(QtGui.QApplication.translate("MainWindow", 'Realizar Busqueda por funcion resumen:', None, QtGui.QApplication.UnicodeUTF8))
	self.label_6.setText(QtGui.QApplication.translate("MainWindow", 'Solo buscar:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", 'No incluir:', None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", 'Por Tipo', None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", 'Mayor que:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow",'Menor que:' , None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", 'Solo incluir archivos con tamaño:', None, QtGui.QApplication.UnicodeUTF8))
	self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", 'Por tamaño', None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("MainWindow", 'Filtros', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", 'Realizar búsqueda', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_666.setText(QtGui.QApplication.translate("MainWindow", 'Cancelar', None, QtGui.QApplication.UnicodeUTF8))
	self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", 'Adicionar tipos de archivos', None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("MainWindow", 'Búsqueda', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("MainWindow",'Borrar Archivos Marcados', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("MainWindow",'Borrar Archivos No Marcados', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("MainWindow",'Borrar Archivos Temporales', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("MainWindow",'Borrar Directorios Vacíos', None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("MainWindow", 'Herramientas', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_66.setToolTip(QtGui.QApplication.translate("MainWindow",'Encontrar' , None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setToolTip(QtGui.QApplication.translate("MainWindow", 'Marcar todos', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setToolTip(QtGui.QApplication.translate("MainWindow", 'Marcar todos menos el primero de cada grupo', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setToolTip(QtGui.QApplication.translate("MainWindow", 'Desmarcar todos', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setToolTip(QtGui.QApplication.translate("MainWindow", 'Opciones de selección para archivos encontrados', None, QtGui.QApplication.UnicodeUTF8))
	self.pushButton_74.setToolTip(QtGui.QApplication.translate("MainWindow", 'Marcar todos menos el más nuevo de cada grupo', None, QtGui.QApplication.UnicodeUTF8))
	self.pushButton_75.setToolTip(QtGui.QApplication.translate("MainWindow", 'Marcar todos menos el más viejo de cada grupo', None, QtGui.QApplication.UnicodeUTF8))
	self.pushButton_88.setToolTip(QtGui.QApplication.translate("MainWindow", 'Añadir otro tipo de archivo', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_85.setToolTip(QtGui.QApplication.translate("MainWindow", 'Excluir otro tipo de archivo', None, QtGui.QApplication.UnicodeUTF8))
	self.pushButton_87.setToolTip(QtGui.QApplication.translate("MainWindow", 'Limpiar Selección', None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_89.setToolTip(QtGui.QApplication.translate("MainWindow", 'Limpiar Selección', None, QtGui.QApplication.UnicodeUTF8))
        self.label_0999.setText(QtGui.QApplication.translate("MainWindow", 'Tamaño en disco:', None, QtGui.QApplication.UnicodeUTF8))
	self.checkBox_5.setText(QtGui.QApplication.translate("MainWindow",'Imágenes', None, QtGui.QApplication.UnicodeUTF8))
	self.checkBox_6.setText(QtGui.QApplication.translate("MainWindow",'Videos', None, QtGui.QApplication.UnicodeUTF8))
	self.checkBox_7.setText(QtGui.QApplication.translate("MainWindow",'Imágenes', None, QtGui.QApplication.UnicodeUTF8))
	self.checkBox_8.setText(QtGui.QApplication.translate("MainWindow",'Videos', None, QtGui.QApplication.UnicodeUTF8))
	self.checkBox_9.setText(QtGui.QApplication.translate("MainWindow",'Audio', None, QtGui.QApplication.UnicodeUTF8))
	self.checkBox_10.setText(QtGui.QApplication.translate("MainWindow",'Audio', None, QtGui.QApplication.UnicodeUTF8))
	self.label_099999 .setText(QtGui.QApplication.translate("MainWindow",'Filtrar por extensión', None, QtGui.QApplication.UnicodeUTF8))
		
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", 'Cantidad de Marcados:', None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow",'Tamaño de los no Marcados:' , None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow",'Tamaño de los Marcados:' , None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", 'Tamaño Total:', None, QtGui.QApplication.UnicodeUTF8))
	self.label_98.setText(QtGui.QApplication.translate("MainWindow", 'Tiempo de Búsqueda:', None, QtGui.QApplication.UnicodeUTF8))
	self.label_988.setText(QtGui.QApplication.translate("MainWindow", 'Archivos Revisados:', None, QtGui.QApplication.UnicodeUTF8))
	self.label_9888.setToolTip(QtGui.QApplication.translate("MainWindow",'Directorios Vacíos:', None, QtGui.QApplication.UnicodeUTF8))
	self.label_98888.setToolTip(QtGui.QApplication.translate("MainWindow", 'Temporales:', None, QtGui.QApplication.UnicodeUTF8))
	
        MainWindow.setWindowTitle("OnlyOne")
