# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Dec 11 11:55:20 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import pickle
fichero=open("language.sp","r")
language=pickle.load(fichero)
fichero.close()

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
	
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.setGeometry(QtCore.QRect(60,150,907, 550))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(907, 550))
        MainWindow.setMaximumSize(QtCore.QSize(907, 550))
	icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(0.95)
        MainWindow.setToolTip(_fromUtf8(""))
        MainWindow.setStatusTip(_fromUtf8(""))
        MainWindow.setWhatsThis(_fromUtf8(""))
        MainWindow.setAccessibleName(_fromUtf8(""))
        MainWindow.setAccessibleDescription(_fromUtf8(""))
        MainWindow.setStyleSheet(_fromUtf8("background-color: #ffffff;\n"))
        MainWindow.setWindowFilePath(_fromUtf8(""))
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)	
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
	
	self.treeView = QtGui.QTreeView(self.centralwidget)
	self.treeView.setStyleSheet(_fromUtf8("padding-left: -22px;padding-right: -700px;font-size: 11px;"))
	#self.treeView.setGeometry(QtCore.QRect(252, 122, 343,408))
	self.treeView.setGeometry(QtCore.QRect(252, 122, 663,408))
	font = QtGui.QFont()
	font.setBold(True)
	font.setWeight(12)
	self.treeView.setObjectName(_fromUtf8("treeView"))
	self.treeView.setMaximumSize(QtCore.QSize(663, 408))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 911, 51))
        self.groupBox.setStyleSheet(_fromUtf8("background-color: #555555;"))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(860, 10, 41, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.pushButton.setStyleSheet(_fromUtf8("background-color:#ebebeb;\n"
"border-radius: 15px;"))
        self.pushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/f12923088.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 26))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 10, 41, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.pushButton_2.setStyleSheet(_fromUtf8("background-color:#ebebeb;\n"
"border-radius: 15px;"))
        self.pushButton_2.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/f12904928.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(810, 10, 41, 30))
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_3.setStyleSheet(_fromUtf8("background-color:#ebebeb;\n"
"border-radius: 15px;"))
        self.pushButton_3.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/f2966728.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(36, 26))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(700, 10, 41, 30))
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_4.setStyleSheet(_fromUtf8("background-color:#ebebeb;\n"
"border-radius: 15px;"))
        self.pushButton_4.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("img/f12864728.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(21, 26))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
	self.toolButton = QtGui.QToolButton(self.groupBox)
        self.toolButton.setGeometry(QtCore.QRect(727, 19, 13, 13))
	self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setStyleSheet(_fromUtf8("background-color:#ffffff;\n"
"border-radius: 15px;"))
        self.toolButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/f8577008.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.toolButton_2 = QtGui.QToolButton(self.groupBox)
        self.toolButton_2.setGeometry(QtCore.QRect(701, 19, 13, 13))
	self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_2.setStyleSheet(_fromUtf8("background-color:#ebebeb;\n"
"border-radius: 15px;"))
        self.toolButton_2.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/f8577009.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(650, 10, 41, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet(_fromUtf8("background-color:#ebebeb;\n"
"border-radius: 15px;"))
        self.pushButton_5.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("img/f13140384.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(750, 0, 3, 51))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(0, 20, 650, 3))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.groupBox)
        self.line_3.setGeometry(QtCore.QRect(0, 30, 650, 3))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
	self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(8, 0, 50, 50))
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setPixmap(QtGui.QPixmap(_fromUtf8("img/logo.png")))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(0, 60, 251, 300))
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.toolBox.setStyleSheet(_fromUtf8("background-color:#f7f7f7;\n"
"color:#094eb6;"))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 251, 207))
        self.page.setObjectName(_fromUtf8("page"))
        self.tabWidget = QtGui.QTabWidget(self.page)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 241, 201))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(10, 20, 221, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 220, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
	
	self.kurlrequester = KUrlRequester(self.tab_3)
        self.kurlrequester.setGeometry(QtCore.QRect(10, 40, 211, 27))
        self.kurlrequester.setObjectName(_fromUtf8("kurlrequester"))
	self.kurlrequester.setMode(KFile.Directory);
	self.kurlrequester_2 = KUrlRequester(self.tab_3)
        self.kurlrequester_2.setGeometry(QtCore.QRect(10, 110, 201, 27))
        self.kurlrequester_2.setObjectName(_fromUtf8("kurlrequester"))
	self.kurlrequester_2.setMode(KFile.Directory);
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(130, 10, 71, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
	
	self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 101, 23))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 30, 101, 23))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
	self.pushButton_88 = QtGui.QPushButton(self.tab)
        self.pushButton_88.setGeometry(QtCore.QRect(44, 60, 33, 27))
        self.pushButton_88.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/f11062728.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_88.setIcon(icon1)
	self.pushButton_88.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_88.setObjectName(_fromUtf8("pushButton_88"))
        self.pushButton_85 = QtGui.QPushButton(self.tab)
        self.pushButton_85.setGeometry(QtCore.QRect(164, 60, 33, 27))
        self.pushButton_85.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/f11062728.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_85.setIcon(icon2)
	self.pushButton_85.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_85.setObjectName(_fromUtf8("pushButton_85"))
	
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 90, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 110,90, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox.setGeometry(QtCore.QRect(90, 60, 101, 23))
	self.doubleSpinBox.setMaximum(999999999999999999.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.tab_2)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(90, 110, 101, 23))
	self.doubleSpinBox_2.setMaximum(9999999999999999999.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 200, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("img/f6178612.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page, icon5, _fromUtf8(""))
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 251, 207))
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.pushButton_6 = QtGui.QPushButton(self.page_2)
        self.pushButton_6.setGeometry(QtCore.QRect(5, 20, 200, 27))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("img/f11046904.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.page_2)
        self.pushButton_7.setGeometry(QtCore.QRect(5, 70, 200, 27))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
	self.progressBar = QtGui.QProgressBar(self.page_2)
	self.progressBar.setRange(0,1)
	self.progressBar.setGeometry(QtCore.QRect(207, 22, 40, 22))
	self.progressBar.setObjectName(_fromUtf8("progressBar"))
	self.progressBar.show()
	self.progressBar.setVisible(True)
	self.kpixmapsequencewidget_2 = KPixmapSequenceWidget(self.page_2)
        self.kpixmapsequencewidget_2.setGeometry(QtCore.QRect(220, 72, 22, 22))
        self.kpixmapsequencewidget_2.setObjectName(_fromUtf8("kpixmapsequencewidget_2"))
	self.kpixmapsequencewidget_2.setVisible(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("img/f6618952.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon7)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("img/f13138288.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_2, icon8, _fromUtf8(""))
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 251, 207))
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.pushButton_14 = QtGui.QPushButton(self.page_3)
        self.pushButton_14.setGeometry(QtCore.QRect(20, 10, 211, 27))
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("img/f6447422.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon9)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(self.page_3)
        self.pushButton_15.setGeometry(QtCore.QRect(20, 50, 211, 27))
        self.pushButton_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_15.setIcon(icon9)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton(self.page_3)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 90, 211, 27))
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setIcon(icon9)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.pushButton_17 = QtGui.QPushButton(self.page_3)
        self.pushButton_17.setGeometry(QtCore.QRect(20, 130, 211, 27))
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setIcon(icon9)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("img/f13139072.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_3, icon10, _fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 50, 661, 41))
        self.groupBox_2.setStyleSheet(_fromUtf8("background-color:#2c88ed;"))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pushButton_66 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_66.setGeometry(QtCore.QRect(520, 6, 47, 31))
        self.pushButton_66.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_66.setText(_fromUtf8(""))
        icon66 = QtGui.QIcon()
        icon66.addPixmap(QtGui.QPixmap(_fromUtf8("img/f12860504.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_66.setIcon(icon66)
        self.pushButton_66.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_66.setObjectName(_fromUtf8("pushButton_10"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(400, 10, 113, 23))
        self.lineEdit.setStyleSheet(_fromUtf8("background-color:#ffffff;"))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pushButton_10 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 6, 47, 31))
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("img/f8576560.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon11)
        self.pushButton_10.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_11.setGeometry(QtCore.QRect(80, 6, 47, 31))
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("img/f8576576.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon12)
        self.pushButton_11.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_12 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_12.setGeometry(QtCore.QRect(150, 6, 47, 31))
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("img/f8576728.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon13)
        self.pushButton_12.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_13.setGeometry(QtCore.QRect(600, 6, 47, 31))
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setText(_fromUtf8(""))
        self.pushButton_13.setIcon(icon11)
        self.pushButton_13.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 360, 251, 191))
        self.groupBox_3.setStyleSheet(_fromUtf8("background-color:#d0deed;"))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 160, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 40, 160, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(10, 70, 160, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(10, 100, 160, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(10, 130, 160, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(10, 160, 160, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
	self.line_4 = QtGui.QFrame(self.groupBox_3)
        self.line_4.setGeometry(QtCore.QRect(10, 30, 230, 3))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.groupBox_3)
        self.line_5.setGeometry(QtCore.QRect(10, 60, 230, 3))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.groupBox_3)
        self.line_6.setGeometry(QtCore.QRect(10, 90, 230, 3))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_8 = QtGui.QFrame(self.groupBox_3)
        self.line_8.setGeometry(QtCore.QRect(10, 120, 230, 3))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_9 = QtGui.QFrame(self.groupBox_3)
        self.line_9.setGeometry(QtCore.QRect(10, 150, 230, 3))
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_11 = QtGui.QFrame(self.groupBox_3)
        self.line_11.setGeometry(QtCore.QRect(10, 180, 230, 3))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
	self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(165, 10, 79, 17))
	self.label_8.setStyleSheet(_fromUtf8("color:#1a528f;\n"
"font-weight:bold"))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(165, 40, 79, 17))
	self.label_9.setStyleSheet(_fromUtf8("color:#1a528f;\n"
"font-weight:bold"))
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(165, 70, 79, 17))
	self.label_10.setStyleSheet(_fromUtf8("color:#1a528f;\n"
"font-weight:bold"))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(165, 100, 88, 17))
	self.label_11.setStyleSheet(_fromUtf8("color:#1a528f;\n"
"font-weight:bold"))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(165, 130, 88, 17))
	self.label_12.setStyleSheet(_fromUtf8("color:#1a528f;\n"
"font-weight:bold"))
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(165, 160, 88, 17))
	self.label_13.setStyleSheet(_fromUtf8("color:#1a528f;\n"
"font-weight:bold"))
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(250, 50, 3, 500))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(250, 530, 661, 20))
        self.groupBox_4.setStyleSheet(_fromUtf8("background-color:#2c88ed;"))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.line_12 = QtGui.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(250, 112, 656, 3))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(253, 90, 661, 21))
        self.groupBox_5.setStyleSheet(_fromUtf8("background-color:#aaaaaa;"))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(150, 3, 90, 17))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(360, 3, 40, 17))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(460, 3, 90, 17))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(550, 3, 90, 20))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.line_13 = QtGui.QFrame(self.groupBox_5)
        self.line_13.setGeometry(QtCore.QRect(530, 0, 3, 21))
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.line_14 = QtGui.QFrame(self.groupBox_5)
        self.line_14.setGeometry(QtCore.QRect(430, 0, 3, 21))
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.line_15 = QtGui.QFrame(self.groupBox_5)
        self.line_15.setGeometry(QtCore.QRect(0, 0, 3, 21))
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.line_10 = QtGui.QFrame(self.groupBox_5)
        self.line_10.setGeometry(QtCore.QRect(340, 0, 3, 20))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_16 = QtGui.QFrame(self.groupBox_5)
        self.line_16.setGeometry(QtCore.QRect(20, 0, 3, 20))
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(253, 112, 661, 10))
        self.groupBox_6.setStyleSheet(_fromUtf8("background-color:#aaaaaa;"))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.line_17 = QtGui.QFrame(self.groupBox_6)
        self.line_17.setGeometry(QtCore.QRect(340, 0, 3, 10))
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.line_18 = QtGui.QFrame(self.groupBox_6)
        self.line_18.setGeometry(QtCore.QRect(430, 0, 3, 10))
        self.line_18.setFrameShape(QtGui.QFrame.VLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.line_19 = QtGui.QFrame(self.groupBox_6)
        self.line_19.setGeometry(QtCore.QRect(530, 0, 3, 10))
        self.line_19.setFrameShape(QtGui.QFrame.VLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.line_20 = QtGui.QFrame(self.groupBox_6)
        self.line_20.setGeometry(QtCore.QRect(20, 0, 3, 10))
        self.line_20.setFrameShape(QtGui.QFrame.VLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_8.setGeometry(QtCore.QRect(470, 0, 10, 10))
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("img/f6864248.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon14)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_9.setGeometry(QtCore.QRect(380, 0, 10, 10))
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setText(_fromUtf8(""))
        self.pushButton_9.setIcon(icon14)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_18 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_18.setGeometry(QtCore.QRect(590, 0, 10, 10))
        self.pushButton_18.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_18.setText(_fromUtf8(""))
        self.pushButton_18.setIcon(icon14)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
	
	self.label_98 = QtGui.QLabel(self.groupBox_4)
        self.label_98.setGeometry(QtCore.QRect(1, 2, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_98.setFont(font)
	self.label_98.setVisible(False)
        self.label_98.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 13px;"))
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.label_99 = QtGui.QLabel(self.groupBox_4)
        self.label_99.setGeometry(QtCore.QRect(140, 2, 59, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_99.setFont(font)
        self.label_99.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 13px;"))
        self.label_99.setText(_fromUtf8(""))
        self.label_99.setObjectName(_fromUtf8("label_99"))
	self.label_988 = QtGui.QLabel(self.groupBox_4)
        self.label_988.setGeometry(QtCore.QRect(220, 2, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_988.setFont(font)
	self.label_988.setVisible(False)
        self.label_988.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 13px;"))
        self.label_988.setObjectName(_fromUtf8("label_988"))
        self.label_999 = QtGui.QLabel(self.groupBox_4)
        self.label_999.setGeometry(QtCore.QRect(350, 2, 59, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_999.setFont(font)
        self.label_999.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 13px;"))
        self.label_999.setText(_fromUtf8(""))
        self.label_999.setObjectName(_fromUtf8("label_999"))
	self.label_9888 = QtGui.QLabel(self.groupBox_4)
        self.label_9888.setGeometry(QtCore.QRect(400, 2, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9888.setFont(font)
	self.label_9888.setVisible(False)
        self.label_9888.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 13px;"))
        self.label_9888.setObjectName(_fromUtf8("label_9888"))
        self.label_9999 = QtGui.QLabel(self.groupBox_4)
        self.label_9999.setGeometry(QtCore.QRect(520, 2, 59, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9999.setFont(font)
        self.label_9999.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 13px;"))
        self.label_9999.setText(_fromUtf8(""))
        self.label_9999.setObjectName(_fromUtf8("label_999"))
	self.label_98888 = QtGui.QLabel(self.groupBox_4)
        self.label_98888.setGeometry(QtCore.QRect(545, 2, 151, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_98888.setFont(font)
	self.label_98888.setVisible(False)
        self.label_98888.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 13px;"))
        self.label_98888.setObjectName(_fromUtf8("label_98888"))
        self.label_99999 = QtGui.QLabel(self.groupBox_4)
        self.label_99999.setGeometry(QtCore.QRect(625, 2, 59, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_99999.setFont(font)
        self.label_99999.setStyleSheet(_fromUtf8("color:#ffffff;font-size: 13px;"))
        self.label_99999.setText(_fromUtf8(""))
        self.label_99999.setObjectName(_fromUtf8("label_9999"))
	
	self.label_100 = QtGui.QLabel(self.tab_2)
        self.label_100.setGeometry(QtCore.QRect(200, 64, 21, 17))
        self.label_100.setObjectName(_fromUtf8("label_14"))
        self.label_101= QtGui.QLabel(self.tab_2)
        self.label_101.setGeometry(QtCore.QRect(200, 114, 21, 17))
        self.label_101.setObjectName(_fromUtf8("label_101"))
	
	self.listWidget_3 = QtGui.QListWidget(self.tab)
        self.listWidget_3.setGeometry(QtCore.QRect(10, 90, 101, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_3.sizePolicy().hasHeightForWidth())
        self.listWidget_3.setSizePolicy(sizePolicy)
        self.listWidget_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listWidget_3.setFrameShape(QtGui.QFrame.Box)
        self.listWidget_3.setFrameShadow(QtGui.QFrame.Raised)
        self.listWidget_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_3.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.listWidget_3.setTabKeyNavigation(True)
        self.listWidget_3.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listWidget_3.setTextElideMode(QtCore.Qt.ElideNone)
        self.listWidget_3.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.listWidget_3.setProperty("isWrapping", False)
        self.listWidget_3.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget_3.setLayoutMode(QtGui.QListView.Batched)
        self.listWidget_3.setViewMode(QtGui.QListView.ListMode)
        self.listWidget_3.setModelColumn(0)
        self.listWidget_3.setUniformItemSizes(True)
        self.listWidget_3.setWordWrap(False)
        self.listWidget_3.setSelectionRectVisible(False)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget"))
	self.listWidget_3.setDefaultDropAction(QtCore.Qt.IgnoreAction)
	self.listWidget_4 = QtGui.QListWidget(self.tab)
        self.listWidget_4.setGeometry(QtCore.QRect(130, 90, 101, 71))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_4.sizePolicy().hasHeightForWidth())
        self.listWidget_4.setSizePolicy(sizePolicy)
        self.listWidget_4.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listWidget_4.setFrameShape(QtGui.QFrame.Box)
        self.listWidget_4.setFrameShadow(QtGui.QFrame.Raised)
        self.listWidget_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_4.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.listWidget_4.setTabKeyNavigation(True)
        self.listWidget_4.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listWidget_4.setTextElideMode(QtCore.Qt.ElideNone)
        self.listWidget_4.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.listWidget_4.setProperty("isWrapping", False)
        self.listWidget_4.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget_4.setLayoutMode(QtGui.QListView.Batched)
        self.listWidget_4.setViewMode(QtGui.QListView.ListMode)
        self.listWidget_4.setModelColumn(0)
        self.listWidget_4.setUniformItemSizes(True)
        self.listWidget_4.setWordWrap(False)
        self.listWidget_4.setSelectionRectVisible(False)
        self.listWidget_4.setObjectName(_fromUtf8(""))
	self.listWidget_4.setDefaultDropAction(QtCore.Qt.IgnoreAction)
	
	self.listWidget = QtGui.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(10, 50, 101, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listWidget.setFrameShape(QtGui.QFrame.Box)
        self.listWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.listWidget.setTabKeyNavigation(True)
        self.listWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.listWidget.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget.setLayoutMode(QtGui.QListView.Batched)
        self.listWidget.setViewMode(QtGui.QListView.ListMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setWordWrap(False)
        self.listWidget.setSelectionRectVisible(False)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))	
	self.listWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
	self.listWidget.setVisible(False)
	self.listWidget_2 = QtGui.QListWidget(self.tab)
        self.listWidget_2.setGeometry(QtCore.QRect(130, 50, 101, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_2.sizePolicy().hasHeightForWidth())
        self.listWidget_2.setSizePolicy(sizePolicy)
        self.listWidget_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.listWidget_2.setFrameShape(QtGui.QFrame.Box)
        self.listWidget_2.setFrameShadow(QtGui.QFrame.Raised)
        self.listWidget_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_2.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.EditKeyPressed|QtGui.QAbstractItemView.SelectedClicked)
        self.listWidget_2.setTabKeyNavigation(True)
        self.listWidget_2.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.listWidget_2.setTextElideMode(QtCore.Qt.ElideNone)
        self.listWidget_2.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.listWidget_2.setProperty("isWrapping", False)
        self.listWidget_2.setResizeMode(QtGui.QListView.Adjust)
        self.listWidget_2.setLayoutMode(QtGui.QListView.Batched)
        self.listWidget_2.setViewMode(QtGui.QListView.ListMode)
        self.listWidget_2.setModelColumn(0)
        self.listWidget_2.setUniformItemSizes(True)
        self.listWidget_2.setWordWrap(False)
        self.listWidget_2.setSelectionRectVisible(False)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget"))
	self.listWidget_2.setDefaultDropAction(QtCore.Qt.IgnoreAction)
	self.listWidget_2.setVisible(False)

	self.groupBox_55 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_55.setGeometry(QtCore.QRect(550, 30, 101, 301))
        self.groupBox_55.setStyleSheet(_fromUtf8("background-color: #d0deed;"))
        self.groupBox_55.setTitle(_fromUtf8(""))
        self.groupBox_55.setObjectName(_fromUtf8("groupBox_55"))
	self.groupBox_55.setVisible(False)	
	self.pushButton_40 = QtGui.QPushButton(self.groupBox_55)
        self.pushButton_40.setGeometry(QtCore.QRect(0, 0, 101, 31))
        self.pushButton_40.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/flags/españa.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_40.setIcon(icon)
        self.pushButton_40.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_40.setObjectName(_fromUtf8("pushButton_40"))
        self.pushButton_41 = QtGui.QPushButton(self.groupBox_55)
        self.pushButton_41.setGeometry(QtCore.QRect(0, 30, 101, 31))
        self.pushButton_41.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/flags/inglaterra.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_41.setIcon(icon1)
        self.pushButton_41.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_41.setObjectName(_fromUtf8("pushButton_41"))
        self.pushButton_42 = QtGui.QPushButton(self.groupBox_55)
        self.pushButton_42.setGeometry(QtCore.QRect(0, 60, 101, 31))
        self.pushButton_42.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/flags/china.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_42.setIcon(icon2)
        self.pushButton_42.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_42.setObjectName(_fromUtf8("pushButton_42"))
        self.pushButton_43 = QtGui.QPushButton(self.groupBox_55)
        self.pushButton_43.setGeometry(QtCore.QRect(0, 90, 101, 31))
        self.pushButton_43.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("img/flags/japon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_43.setIcon(icon3)
        self.pushButton_43.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_43.setObjectName(_fromUtf8("pushButton_43"))
        self.pushButton_45 = QtGui.QPushButton(self.groupBox_55)
        self.pushButton_45.setGeometry(QtCore.QRect(0, 120, 101, 31))
        self.pushButton_45.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("img/flags/alemania.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_45.setIcon(icon5)
        self.pushButton_45.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_45.setObjectName(_fromUtf8("pushButton_45"))
        self.pushButton_48= QtGui.QPushButton(self.groupBox_55)
        self.pushButton_48.setGeometry(QtCore.QRect(0, 150, 101, 31))
        self.pushButton_48.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("img/flags/rusia.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_48.setIcon(icon6)
        self.pushButton_48.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_48.setObjectName(_fromUtf8("pushButton_48"))
        self.pushButton_47 = QtGui.QPushButton(self.groupBox_55)
        self.pushButton_47.setGeometry(QtCore.QRect(0, 180, 101, 31))
        self.pushButton_47.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("img/flags/italia.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_47.setIcon(icon7)
        self.pushButton_47.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_47.setObjectName(_fromUtf8("pushButton_47"))
        self.pushButton_49 = QtGui.QPushButton(self.groupBox_55)
        self.pushButton_49.setGeometry(QtCore.QRect(0, 210, 101, 31))
        self.pushButton_49.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("img/flags/portugal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_49.setIcon(icon4)
        self.pushButton_49.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_49.setObjectName(_fromUtf8("pushButton_49"))
        self.pushButton_46 = QtGui.QPushButton(self.groupBox_55)
        self.pushButton_46.setGeometry(QtCore.QRect(0, 240, 101, 31))
        self.pushButton_46.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("img/flags/francia.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_46.setIcon(icon8)
        self.pushButton_46.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_46.setObjectName(_fromUtf8("pushButton_46"))
        self.pushButton_44 = QtGui.QPushButton(self.groupBox_55)
        self.pushButton_44.setGeometry(QtCore.QRect(0, 270, 101, 31))
        self.pushButton_44.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("img/flags/arabe.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_44.setIcon(icon9)
        self.pushButton_44.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_44.setObjectName(_fromUtf8("pushButton_44"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionAyuda = QtGui.QAction(MainWindow)
        self.actionAyuda.setObjectName(_fromUtf8("actionAyuda"))
        self.actionFacebook = QtGui.QAction(MainWindow)
        self.actionFacebook.setObjectName(_fromUtf8("actionFacebook"))
        self.actionBlog = QtGui.QAction(MainWindow)
        self.actionBlog.setObjectName(_fromUtf8("actionBlog"))
        self.actionAbaut = QtGui.QAction(MainWindow)
        self.actionAbaut.setObjectName(_fromUtf8("actionAbaut"))
        self.actionEspannol = QtGui.QAction(MainWindow)
        self.actionEspannol.setObjectName(_fromUtf8("actionEspannol"))
        self.actionEnglish = QtGui.QAction(MainWindow)
        self.actionEnglish.setObjectName(_fromUtf8("actionEnglish"))
        self.actionFrench = QtGui.QAction(MainWindow)
        self.actionFrench.setObjectName(_fromUtf8("actionFrench"))
        self.actionItali = QtGui.QAction(MainWindow)
        self.actionItali.setObjectName(_fromUtf8("actionItali"))

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OnlyOne", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", language[29], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setToolTip(QtGui.QApplication.translate("MainWindow", language[27], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setToolTip(QtGui.QApplication.translate("MainWindow", language[28], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setToolTip(QtGui.QApplication.translate("MainWindow", language[26], None, QtGui.QApplication.UnicodeUTF8))
	self.toolButton.setToolTip(QtGui.QApplication.translate("MainWindow", language[26]+"++", None, QtGui.QApplication.UnicodeUTF8))
	self.toolButton_2.setToolTip(QtGui.QApplication.translate("MainWindow", language[26]+"--", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setToolTip(QtGui.QApplication.translate("MainWindow", language[25], None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", language[4], None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", language[5], None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", language[1], None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", language[6], None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", language[7], None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", language[2], None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", language[9], None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", language[10], None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", language[8], None, QtGui.QApplication.UnicodeUTF8))
	self.label_100.setText(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_101.setText(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", language[3], None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("MainWindow", language[0], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", language[12], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", language[13], None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("MainWindow", language[11], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("MainWindow",language[15], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("MainWindow",language[16], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("MainWindow",language[17], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("MainWindow",language[18], None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("MainWindow", language[14], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_66.setToolTip(QtGui.QApplication.translate("MainWindow", language[39], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setToolTip(QtGui.QApplication.translate("MainWindow", language[30], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setToolTip(QtGui.QApplication.translate("MainWindow", language[31], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setToolTip(QtGui.QApplication.translate("MainWindow", language[32], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setToolTip(QtGui.QApplication.translate("MainWindow", language[33], None, QtGui.QApplication.UnicodeUTF8))
	self.pushButton_88.setToolTip(QtGui.QApplication.translate("MainWindow", language[41], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_85.setToolTip(QtGui.QApplication.translate("MainWindow", language[42], None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", language[19], None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", language[20], None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", language[21], None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", language[22], None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", language[23], None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", language[24], None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", language[34], None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", language[35], None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", language[36], None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", language[37], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setToolTip(QtGui.QApplication.translate("MainWindow", language[38], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setToolTip(QtGui.QApplication.translate("MainWindow", language[38], None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_18.setToolTip(QtGui.QApplication.translate("MainWindow", language[38], None, QtGui.QApplication.UnicodeUTF8))
	self.label_98.setText(QtGui.QApplication.translate("MainWindow", language[40], None, QtGui.QApplication.UnicodeUTF8))
	self.label_988.setText(QtGui.QApplication.translate("MainWindow", "Archivos Revisados:", None, QtGui.QApplication.UnicodeUTF8))
	self.label_9888.setText(QtGui.QApplication.translate("MainWindow", "Directorios Vacios:", None, QtGui.QApplication.UnicodeUTF8))
	self.label_98888.setText(QtGui.QApplication.translate("MainWindow", "Temporales:", None, QtGui.QApplication.UnicodeUTF8))
	
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OnlyOne", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_40.setText(QtGui.QApplication.translate("MainWindow", "Español      ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_41.setText(QtGui.QApplication.translate("MainWindow", "English        ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_42.setText(QtGui.QApplication.translate("MainWindow", "中国的          ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_43.setText(QtGui.QApplication.translate("MainWindow", "日本の         ", None, QtGui.QApplication.UnicodeUTF8))        
        self.pushButton_45.setText(QtGui.QApplication.translate("MainWindow", "Deutsch      ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_48.setText(QtGui.QApplication.translate("MainWindow", "Pусский    ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_47.setText(QtGui.QApplication.translate("MainWindow", "Italiano       ", None, QtGui.QApplication.UnicodeUTF8))
	self.pushButton_49.setText(QtGui.QApplication.translate("MainWindow", "Português ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_46.setText(QtGui.QApplication.translate("MainWindow", "Français      ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_44.setText(QtGui.QApplication.translate("MainWindow", "العربية           ", None, QtGui.QApplication.UnicodeUTF8))
	
	
from PyKDE4.kio import KUrlRequester,KFile
from PyKDE4.kdeui import KPixmapSequenceWidget, KFilterProxySearchLine
